// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./views/error/404.vue')['default']
    BookDetail: typeof import('./views/product/book/BookDetail.vue')['default']
    BookInfoDetail: typeof import('./views/product/book/BookInfoDetail.vue')['default']
    BookList: typeof import('./views/product/book/BookList.vue')['default']
    BookSaleDetail: typeof import('./views/product/book/BookSaleDetail.vue')['default']
    BreadCrumb: typeof import('./layout/header/BreadCrumb.vue')['default']
    Collapse: typeof import('./layout/header/Collapse.vue')['default']
    DashBoard: typeof import('./layout/dashboard/DashBoard.vue')['default']
    Deal: typeof import('./views/company/deal.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Forget: typeof import('./views/login/Forget.vue')['default']
    Header: typeof import('./layout/header/Header.vue')['default']
    Login: typeof import('./views/login/Login.vue')['default']
    MenuBar: typeof import('./layout/menu/MenuBar.vue')['default']
    MenuItem: typeof import('./layout/menu/MenuItem.vue')['default']
    PressList: typeof import('./views/product/press/PressList.vue')['default']
    SingleUpload: typeof import('./components/SingleUpload.vue')['default']
    Staff: typeof import('./views/company/staff.vue')['default']
    Tabs: typeof import('./layout/tabs/Tabs.vue')['default']
    Undefined: typeof import('./layout/index.vue')['default']
    UserInfo: typeof import('./layout/header/UserInfo.vue')['default']
  }
}

export { }
